spring:
  datasource:
    url: postgresql://postgres:nDsikcIeEdscIixOVtnUhKFwQApRzrBO@ballast.proxy.rlwy.net:27671/railway
    username: ${PGUSER}
    password: PGPASSWORD=nDsikcIeEdscIixOVtnUhKFwQApRzrBO psql -h ballast.proxy.rlwy.net -U postgres -p 27671 -d railway
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #na primeira vez colocar create, depois colocar validate para apenas acessar ao invés de ficar criando as tabelas toda vez

   #  para conectar com Railwai abrir arquivos de configuração e execução
   # duplicar o application DEV e renomear para application PRD e customizar as variáveis de ambiente colocando as informações fornecidas pelo Railway